
```{r set_options_global, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r load_libraries_global, include=FALSE}
library(tidyverse)
library(collapse)
library(patchwork)
library(scico)
library(metR)
```

```{r define_updata_paths_utilities, include = FALSE}
path_functions      <- "/nfs/kryo/work/updata/emlr_cant/utilities/functions/"
path_files          <- "/nfs/kryo/work/updata/emlr_cant/utilities/files/"
```

```{r read_basinmask_file_global, include = FALSE}
basinmask <-
  read_csv(paste(path_files,
                 "basin_mask_WOA18.csv",
                 sep = ""))
```

```{r read_section_coordinates_global, include = FALSE}
section_global_coordinates <-
  read_csv(paste(path_files,
                 "section_global_coordinates.csv",
                 sep = ""))
```

```{r read_ggplot_basemap_global, include = FALSE}
map <-
  read_rds(paste(path_files,
                 "map_landmask_WOA18.rds",
                 sep = ""))
```

```{r read_params_global, include = FALSE}
params_global <-
  read_rds(paste(path_files,
                 "params_global.rds",
                 sep = ""))
```

```{r read_functions_global, include = FALSE}

source(paste(path_functions,
             "plotting_functions.R",
             sep = ""))

source(paste(path_functions,
             "mapping_functions.R",
             sep = ""))

source(paste(path_functions,
             "biogeochemical_functions.R",
             sep = ""))

```

```{r set_ggplot_theme_global, include = FALSE}
theme_set(theme_bw())
```
